@Service.Auth_HostAddress = https://localhost:7068

### Test Login API
POST {{Service.Auth_HostAddress}}/api/Auth/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password123!"
}