@EasyTMS.Auth.AppHost_HostAddress = http://localhost:5093

### Index API

GET {{EasyTMS.Auth.AppHost_HostAddress}}/
Accept: application/json

### Health Check API

GET {{EasyTMS.Auth.AppHost_HostAddress}}/health
Accept: application/json
