<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EasyTMS.Common\EasyTMS.Common.Web\EasyTMS.Common.Web.csproj" />
    <ProjectReference Include="..\EasyTMS.Auth.BusinessImplement\EasyTMS.Auth.BusinessImplement.csproj" />
    <ProjectReference Include="..\EasyTMS.Auth.Controllers\EasyTMS.Auth.Controllers.csproj" />
  </ItemGroup>

</Project>
