@Service.Auth_HostAddress = https://localhost:7068

### Test Sign Up API
POST {{Service.Auth_HostAddress}}/api/Auth/SignUp
Content-Type: application/json

{
  "userName": "top1server",
  "password": "123456",
  "fullName": "EasyTMS Administrator",
  "email": "top1server@example.com",
  "phone": "0912345678",
  "address": "Ho Chi Minh City"
}

### Test Sign Up API (test case 2)

POST {{Service.Auth_HostAddress}}/api/Auth/SignUp
Content-Type: application/json

{
  "userName": "tester1",
  "password": "123456",
  "fullName": "Test 1",
  "email": "test1@example.com",
  "phone": "0912345678",
  "address": "Ho Chi Minh City"
}

###

### Test Login API
POST {{Service.Auth_HostAddress}}/api/Auth/Login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password123!"
}